#!/bin/bash

wallet start

cli wallet open -n violetstairn
cli wallet open -n violetstairs
cli wallet open -n owdinnetwork

cat  ~/eosio-wallet/violetstairn.passwd | cli wallet unlock -n violetstairn
cat  ~/eosio-wallet/violetstairs.passwd | cli wallet unlock -n violetstairs
cat  ~/eosio-wallet/owdinnetwork.passwd | cli wallet unlock -n owdinnetwork
